VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "Evento"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'***************************************************************************
'*
'*
'* Asignacion con Datos en Timeline
'*
'*
'***************************************************************************
Public vHora As New Collection
Public vTipo As New Collection
Public vIntervalo As New Collection
Public vDescripcion As New Collection
Public vLunes As New Collection
Public vMartes As New Collection
Public vMiercoles As New Collection
Public vJueves As New Collection
Public vViernes As New Collection
Public vSabado As New Collection
Public vDomingo As New Collection
Public vtipod As New Collection



